### ISSUE TITLE
stdarg.h missing with v5.16+ kernels

### ISSUE THREAD

**Issue by xnox** [tseliot/nvidia-graphics-drivers#44]
linux stopped including toolchain headers during build, and instead provides some headers internally.

It means that conftests got extended in recent driver series to check for "<linux/stdarg.h>" vs "<stdarg.h>" and include one or the other as appropriate in the "nv_stdarg.h" header and using that throughout.

390 series appear to be missing that change, and need a backport.

I think this got added between diff nvidia-graphics-drivers-470-470.74/ nvidia-graphics-drivers-470-470.82.00/

**Comment by xnox** [comment]
[kernel.diff.txt](https://github.com/tseliot/nvidia-graphics-drivers/files/8117935/kernel.diff.txt)

This is the relevant diff i think, that needs to be tested against 390 tree.

**Comment by xnox** [comment]
Attempting fix in https://github.com/xnox/nvidia-graphics-drivers/tree/390-5.16 and opened https://bugs.launchpad.net/ubuntu/+source/nvidia-graphics-drivers-418-server/+bug/1961815 to track it too.

**Comment by blastwave** [comment]
It is not at all clear how to fix this problem with something like 418.113 where upon --extract of the "run" file there is no stdarg type file anywhere in the extracted contents. I do see that linux-5.16.12 provides include/linux/stdarg.h in the source tree however what does one do with that in the NVidia sources?  This problem is poorly documented.
