### ISSUE TITLE
535: Installing/upgrading drivers causes display shutdown

### ISSUE THREAD

**Issue by Lastique** [tseliot/nvidia-graphics-drivers#61]
Installing/reinstalling/upgrading 535 series of drivers causes the display to permanently turn off during package installation. In the background, the installation seems to proceed, but the DE becomes broken (I'm on KDE, and plasmashell starts to consume 100% CPU in kernel mode). It looks like the GPU simply shuts down during the installation. After that, I cannot reboot the system other than with a SysRq combination or hard reset.

This happens regardless of whether the driver is installed in the DE or in a secondary console.

I believe, this was introduced with 6778e2e983dd2ac48cc202c536f32c9170461b1e and fa3239ef695d44b3b1c9deec2d793feb507a3aab. Reverting those two commits (i.e. switching back to debhelper 9 and `dh_systemd_enable` instead of `dh_installsystemd`) resolves the issue, the driver becomes installable again, including in DE GUI.

I tried to change the `dh_installsystemd` arguments from `--no-start` to `--restart-after-upgrade`, `--no-restart-after-upgrade` or `-r` - nothing worked, the issue is the same.

Steps to reproduce:

Install/upgrade the driver. Or, if it is already installed, reinstall it with a command like this:

```
sudo apt install --reinstall -y libnvidia-cfg1-535:amd64 libnvidia-common-535 libnvidia-compute-535:amd64 libnvidia-compute-535:i386 libnvidia-decode-535:amd64 libnvidia-decode-535:i386 libnvidia-encode-535:amd64 libnvidia-encode-535:i386 libnvidia-extra-535:amd64 libnvidia-fbc1-535:amd64 libnvidia-fbc1-535:i386 libnvidia-gl-535:amd64 libnvidia-gl-535:i386 nvidia-compute-utils-535 nvidia-dkms-535 nvidia-driver-535 nvidia-firmware-535-535.43.10 nvidia-kernel-common-535 nvidia-kernel-source-535 nvidia-utils-535 xserver-xorg-video-nvidia-535
```

Kubuntu 22.04.

**Comment by tseliot** [comment]
I have pushed a fix for this (all the git branches should be in sync now), but it hasn't been approved in the Ubuntu archive yet. This is being tracked here: https://bugs.launchpad.net/ubuntu/+source/nvidia-graphics-drivers-535-server/+bug/2025640

**Comment by Lastique** [comment]
Thanks, 15b7731c5a072b7c3895535a3d7b0656fb52953a and cf3ed4abdccdf42be36cc9dcf5b5e85c99dbead8 fixed the problem for me.

**Comment by MohammadAdnanAldaas** [comment]
sorry for interrupting. I got same/similar problem here after running software manage update  my second monitor not detected and after long search (Knowing that i am a new Ubunutu user) found that nvidia drivers are not loaded because of security boot is enabled but they are correctly installed.
 
before the update i had never problems like this and i had my security boot always enabled.

info : nvidia/535.113.01, 6.2.0-33-generic, x86_64: installed

so my question is it really seem problem as labeled here? and would it be fixed after this issue is confirmed and merged? or is this another issue? and if yes how could be fixed. 

Thx in advanced

**Comment by tseliot** [comment]
Mohammed: No, your problem is probably due to the fact that the linux-restricted-modules for the kernel were not available when you installed the NVIDIA driver, and you installed the dkms package as a result, hence the problem with secure boot. We have a fix for that too, and it is coming soon.

**Comment by executioner90** [comment]
Really thx for fast replay and explaining.

Have a nice day :smile:

**Comment by executioner90** [comment]
I have installed last updates from Ubuntu. unfortunately my second monitor still does not work if my security boot is enabled. is there anyway to fix this?

some info:

$ nvidia-smi
NVIDIA-SMI has failed because it couldn't communicate with the NVIDIA driver. Make sure that the latest NVIDIA driver is installed and running.

$ sudo modprobe nvidia
modprobe: ERROR: could not insert 'nvidia': Key was rejected by service
 
$ dkms status
nvidia/535.113.01, 5.15.0-86-generic, x86_64: installed
nvidia/535.113.01, 6.2.0-33-generic, x86_64: installed
nvidia/535.113.01, 6.2.0-34-generic, x86_64: installed

$ dpkg -l |grep nvidia
ii  libnvidia-cfg1-535:amd64                         535.113.01-0ubuntu0.22.04.1                  amd64        NVIDIA binary OpenGL/GLX configuration library
ii  libnvidia-common-535                             535.113.01-0ubuntu0.22.04.1                  all          Shared files used by the NVIDIA libraries
ii  libnvidia-compute-535:amd64                      535.113.01-0ubuntu0.22.04.1                  amd64        NVIDIA libcompute package
ii  libnvidia-compute-535:i386                       535.113.01-0ubuntu0.22.04.1                  i386         NVIDIA libcompute package
ii  libnvidia-decode-535:amd64                       535.113.01-0ubuntu0.22.04.1                  amd64        NVIDIA Video Decoding runtime libraries
ii  libnvidia-decode-535:i386                        535.113.01-0ubuntu0.22.04.1                  i386         NVIDIA Video Decoding runtime libraries
ii  libnvidia-encode-535:amd64                       535.113.01-0ubuntu0.22.04.1                  amd64        NVENC Video Encoding runtime library
ii  libnvidia-encode-535:i386                        535.113.01-0ubuntu0.22.04.1                  i386         NVENC Video Encoding runtime library
ii  libnvidia-extra-535:amd64                        535.113.01-0ubuntu0.22.04.1                  amd64        Extra libraries for the NVIDIA driver
ii  libnvidia-fbc1-535:amd64                         535.113.01-0ubuntu0.22.04.1                  amd64        NVIDIA OpenGL-based Framebuffer Capture runtime library
ii  libnvidia-fbc1-535:i386                          535.113.01-0ubuntu0.22.04.1                  i386         NVIDIA OpenGL-based Framebuffer Capture runtime library
ii  libnvidia-gl-535:amd64                           535.113.01-0ubuntu0.22.04.1                  amd64        NVIDIA OpenGL/GLX/EGL/GLES GLVND libraries and Vulkan ICD
ii  libnvidia-gl-535:i386                            535.113.01-0ubuntu0.22.04.1                  i386         NVIDIA OpenGL/GLX/EGL/GLES GLVND libraries and Vulkan ICD
rc  linux-modules-nvidia-535-6.2.0-32-generic        6.2.0-32.32~22.04.1                          amd64        Linux kernel nvidia modules for version 6.2.0-32
ii  linux-modules-nvidia-535-6.2.0-33-generic        6.2.0-33.33~22.04.1+1                        amd64        Linux kernel nvidia modules for version 6.2.0-33
ii  linux-modules-nvidia-535-6.2.0-34-generic        6.2.0-34.34~22.04.1+1                        amd64        Linux kernel nvidia modules for version 6.2.0-34
ii  linux-modules-nvidia-535-generic-hwe-22.04       6.2.0-34.34~22.04.1+1                        amd64        Extra drivers for nvidia-535 for the generic-hwe-22.04 flavour
rc  linux-modules-nvidia-535-server-6.2.0-33-generic 6.2.0-33.33~22.04.1+1                        amd64        Linux kernel nvidia modules for version 6.2.0-33
rc  linux-objects-nvidia-535-6.2.0-32-generic        6.2.0-32.32~22.04.1                          amd64        Linux kernel nvidia modules for version 6.2.0-32 (objects)
ii  linux-objects-nvidia-535-6.2.0-33-generic        6.2.0-33.33~22.04.1+1                        amd64        Linux kernel nvidia modules for version 6.2.0-33 (objects)
ii  linux-objects-nvidia-535-6.2.0-34-generic        6.2.0-34.34~22.04.1+1                        amd64        Linux kernel nvidia modules for version 6.2.0-34 (objects)
ii  linux-objects-nvidia-535-server-6.2.0-33-generic 6.2.0-33.33~22.04.1+1                        amd64        Linux kernel nvidia modules for version 6.2.0-33 (objects)
ii  linux-signatures-nvidia-6.2.0-33-generic         6.2.0-33.33~22.04.1+1                        amd64        Linux kernel signatures for nvidia modules for version 6.2.0-33-generic
ii  linux-signatures-nvidia-6.2.0-34-generic         6.2.0-34.34~22.04.1+1                        amd64        Linux kernel signatures for nvidia modules for version 6.2.0-34-generic
ii  nvidia-compute-utils-535                         535.113.01-0ubuntu0.22.04.1                  amd64        NVIDIA compute utilities
ii  nvidia-dkms-535                                  535.113.01-0ubuntu0.22.04.1                  amd64        NVIDIA DKMS package
ii  nvidia-driver-535                                535.113.01-0ubuntu0.22.04.1                  amd64        NVIDIA driver metapackage
ii  nvidia-firmware-535-535.113.01                   535.113.01-0ubuntu0.22.04.1                  amd64        Firmware files used by the kernel module
ii  nvidia-kernel-common-535                         535.113.01-0ubuntu0.22.04.1                  amd64        Shared files used with the kernel module
ii  nvidia-kernel-source-535                         535.113.01-0ubuntu0.22.04.1                  amd64        NVIDIA kernel source package
ii  nvidia-prime                                     0.8.17.1                                     all          Tools to enable NVIDIA's Prime
ii  nvidia-settings                                  510.47.03-0ubuntu1                           amd64        Tool for configuring the NVIDIA graphics driver
ii  nvidia-utils-535                                 535.113.01-0ubuntu0.22.04.1                  amd64        NVIDIA driver support binaries
ii  screen-resolution-extra                          0.18.2                                       all          Extension for the nvidia-settings control panel
ii  xserver-xorg-video-nvidia-535                    535.113.01-0ubuntu0.22.04.1                  amd64        NVIDIA binary Xorg driver

**Comment by Lastique** [comment]
@executioner90 Please, report this as a separate issue.
